name: Add Issues to Project Backlog

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project Backlog lane
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 1; // Your project number
            const backlogStatusId = 'f75ad846'; // Status ID for Backlog lane
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = context.payload.issue;

            // Only proceed if issue is in the MIaaS repo
            if (repo !== 'MIaaS') return;

            // Only proceed if issue has 'backlog' label
            if (!issue.labels.some(label => label.name === 'backlog')) return;

            // Find the project
            const projects = await github.rest.projects.listForUser({ username: owner });
            const project = projects.data.find(p => p.name === 'MIaaS');
            if (!project) return;

            // Add the issue to the project
            await github.rest.projects.createCard({
              column_id: backlogStatusId,
              content_id: issue.id,
              content_type: 'Issue'
            });
